import json
from pathlib import Path

# Path to your whisper-large-v3 predictions JSON generated by benchmark script
RESULTS_FILE = Path("experiments/whisper-large-v3_results.json")

def inspect_errors(results_path, max_samples=10):
    with open(results_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    print("=" * 80)
    print("ALGERIAN DARIJA ERROR INSPECTION")
    print("=" * 80)
    
    for i, item in enumerate(data[:max_samples]):
        ref = item.get("reference", "")
        pred = item.get("prediction", "")
        wer_val = item.get("wer", 0.0)
        
        print(f"\n[Sample {i+1}] WER: {wer_val:.4f}")
        print(f"  REF : {ref}")
        print(f"  PRED: {pred}")
        print("-" * 80)

if __name__ == "__main__":
    inspect_errors(RESULTS_FILE)